language: android

android:
  components:
    - tools                             # Tools
    - platform-tools                    # Platform tools
    - build-tools-27.0.2                # Build tools version
    - android-27                        # Target SDK version
    - extra-android-m2repository        # Support repo
    - sys-img-armeabi-v7a-android-27    # Emulator

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - openjdk8

before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-26"

script:
  - ./gradlew build --info --stacktrace

#notifications:
  #slack:
    #on_success: always
  #email:
    #dcunha.cyprien@gmail.com

sudo: false

cache:
  directories:
    - $HOME/.gradle

env:
  global:
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)
